namespace FoodDrinkApp.Services;

public static class MockApiConfig
{
    // Replace this with the Resource endpoint generated by mockapi.io.
    // Example: https://682xxxx.mockapi.io/api/v1/foods
    public const string EndpointUrl = "https://69ef00f29163f839f8933f43.mockapi.io/foods";

    public static bool IsConfigured => !string.IsNullOrWhiteSpace(EndpointUrl);
}
